---
# all non secret vars
zfs: {
  poolName: dataPool,
  DISK1: '/dev/disk/by-id/scsi-123abc',
  DISK2: '/dev/disk/by-id/scsi-456def',
  CACHEDISK: '/dev/disk/by-id/scsi-424242ababab',
  poolName2: dataPool2,
  DISK3: '/dev/disk/by-id/scsi-123abc',
  DISK4: '/dev/disk/by-id/scsi-456def',
}

usergroups:
  - family
  - admins

users:
  - {name: 'mainuser', groups: 'family, admins', smbpasswd: 'mainuser'}
  - {name: 'otheruser', groups: 'family', smbpasswd: 'otheruser'}
  - {name: 'thirduser', groups: 'family', smbpasswd: 'thirduser'}
  - {name: 'userNotInGroups', groups: '', smbpasswd: 'userNotInGroups'}

adminuser: mainuser # should be an existing one from above

shared_folders:
  - {name: 'Images', path: '/{{zfs.poolName}}/media/images'}
  - {name: 'movie', path: '/{{zfs.poolName}}/media/movie'}
  - {name: 'Shared folder', path: '/{{zfs.poolName}}/personal/all'}
  - {name: 'Shared Backup Folder', path: '/{{zfs.poolName}}/backup/all'}

shared_folders_group: family
